export const manifestFields = new Set([
  '$schema',
  'schema_id',
  'package_series',
  'release_version',
  'lifecycle_state',
  'validator_version',
  'normative_vocabulary',
  'authority',
  'layout',
  'artifacts',
  'normative_digest',
  'conformance_digest',
  'amendment_policy',
  'conformance',
]);

export const transitionFields = new Set([
  'transition_id',
  'command_or_event',
  'from_state',
  'allowed',
  'actor_authority',
  'preconditions',
  'base_references',
  'emitted_records',
  'filesystem_effects',
  'idempotency',
  'terminal_state',
  'failure_result',
  'recovery',
]);

const authorityByCommand = new Map([
  ['submit', {roles: ['package_author'], quorum: 1, distinct_actors: false, delegation: 'permitted'}],
  ['approve', {roles: ['vault_owner', 'independent_technical_reviewer'], quorum: 2, distinct_actors: true, delegation: 'forbidden'}],
  ['release', {roles: ['release_coordinator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['amend', {roles: ['package_author'], quorum: 1, distinct_actors: false, delegation: 'permitted'}],
  ['record_verdict', {roles: ['conformance_validator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['readback', {roles: ['conformance_validator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['mark_stale', {roles: ['conformance_validator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['supply_fresh_evidence', {roles: ['evidence_supplier'], quorum: 1, distinct_actors: false, delegation: 'permitted'}],
  ['append_operation', {roles: ['semantic_kernel'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_operation', {roles: ['semantic_kernel'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['enqueue_work', {roles: ['work_submitter'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['dispatch_work', {roles: ['scheduler'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['acknowledge_work', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['complete_work', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_work', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['record_retry', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['record_terminal_failure', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['retry_work', {roles: ['scheduler'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['cancel_work', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['resume_work', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['evaluate_readiness', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['dependency_lost', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['start_agent', {roles: ['launchd_supervisor'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['crash_agent', {roles: ['operating_system'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_agent', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['stop_agent', {roles: ['launchd_supervisor'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['open_control_channel', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['submit_control_command', {roles: ['control_client'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['close_control_channel', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['acquire_writer', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['retain_writer', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['release_writer', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['unexpected_exit', {roles: ['operating_system'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['qualifying_failure', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['backoff_elapsed', {roles: ['launchd_supervisor'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['restart_ceiling_reached', {roles: ['launchd_supervisor'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['wake_revalidate', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['emit_doctor_report', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['approve_owner_recovery', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['complete_recovery', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['activate_policy', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['revoke_policy', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['activate_source_profile', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['revoke_source_profile', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['invalidate_source_profile', {roles: ['capture_adapter'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_unapproved_source_profile', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_approved_source_profile', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['prepare', {roles: ['vault_mutation_gate'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['validate', {roles: ['vault_mutation_gate'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['mutate', {roles: ['vault_mutation_gate'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['record_receipt', {roles: ['vault_mutation_gate'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['verify_readback', {roles: ['vault_mutation_gate'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['commit', {roles: ['vault_mutation_gate'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['resume', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['rollback', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['compensate', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['halt_manual_repair', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['bind_generator', {roles: ['conformance_validator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['generate_manifest', {roles: ['reference_vault_generator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['seal_manifest', {roles: ['conformance_validator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_generation', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['plan_redistribution', {roles: ['vault_owner'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['apply_redistribution', {roles: ['reference_vault_generator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_redistribution', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['seal_redistribution', {roles: ['conformance_validator'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['authorize_adapter_attempt', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['transmit_adapter_payload', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['record_adapter_outcome', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['deny_adapter_attempt', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['time_out_adapter_attempt', {roles: ['operating_system'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['authorize_adapter_retry', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['start_adapter_retry', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['exhaust_adapter_retry', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['authorize_adapter_fallback', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['start_adapter_fallback', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['exhaust_adapter_fallback', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['verify_adapter_isolation', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['fail_adapter_canary', {roles: ['mdplace_agent'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['inspect_adapter_recovery', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['recover_adapter_receipt', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
  ['deny_adapter_recovery', {roles: ['foreground_recovery'], quorum: 1, distinct_actors: false, delegation: 'forbidden'}],
]);

const conformanceExecutables = new Set([
  'conformance/digest-bindings.mjs',
  'conformance/evidence-claim-validation.mjs',
  'conformance/evidence-core.mjs',
  'conformance/evidence-envelope-validation.mjs',
  'conformance/evidence-extension.mjs',
  'conformance/evidence-freshness.mjs',
  'conformance/evidence-invocation-validation.mjs',
  'conformance/evidence-recovery-validation.mjs',
  'conformance/evidence-transition-validation.mjs',
  'conformance/amendment-evidence.mjs',
  'conformance/control-plane-checks.mjs',
  'conformance/control-plane-lifecycle-checks.mjs',
  'conformance/control-plane-contract-values.mjs',
  'conformance/control-plane-evidence.mjs',
  'conformance/control-plane-lifecycle-replay.mjs',
  'conformance/control-plane-observer.mjs',
  'conformance/control-plane-observation.mjs',
  'conformance/control-plane-scenario-history.mjs',
  'conformance/child-work-validation.mjs',
  'conformance/control-plane-authentication.mjs',
  'conformance/control-plane-outcome.mjs',
  'conformance/fixture-observer.mjs',
  'conformance/semantic-kernel-authority.mjs',
  'conformance/semantic-kernel-checks.mjs',
  'conformance/semantic-kernel-core.mjs',
  'conformance/semantic-kernel-evidence.mjs',
  'conformance/semantic-kernel-observer.mjs',
  'conformance/semantic-kernel-receipts.mjs',
  'conformance/semantic-kernel-replay.mjs',
  'conformance/json-schema.mjs',
  'conformance/package-checks.mjs',
  'conformance/package-foundation.mjs',
  'conformance/pattern-evaluation.mjs',
  'conformance/processing-policy-checks.mjs',
  'conformance/processing-policy-attempts.mjs',
  'conformance/processing-policy-core.mjs',
  'conformance/processing-policy-decision.mjs',
  'conformance/processing-policy-evidence.mjs',
  'conformance/processing-policy-observer.mjs',
  'conformance/processing-policy-result.mjs',
  'conformance/requirement-checks.mjs',
  'conformance/reference-evidence.mjs',
  'conformance/safe-path.mjs',
  'conformance/schema-error-code.mjs',
  'conformance/schema-instances.mjs',
  'conformance/traceability-checks.mjs',
  'conformance/transition-observer.mjs',
  'conformance/transition-evidence.mjs',
  'conformance/validator-boundary-cases.mjs',
  'conformance/validator-control-plane-cases.mjs',
  'conformance/validator-control-plane-diagnostics-cases.mjs',
  'conformance/validator-control-plane-lifecycle-cases.mjs',
  'conformance/validator-control-plane-observation-cases.mjs',
  'conformance/validator-contract-cases.mjs',
  'conformance/validator-processing-policy-boundary-cases.mjs',
  'conformance/validator-processing-policy-cases.mjs',
  'conformance/validator-coderabbit-review-cases.mjs',
  'conformance/validator-evidence-cases.mjs',
  'conformance/validator-evidence-domain-invariants.mjs',
  'conformance/validator-evidence-envelope-integrity.mjs',
  'conformance/validator-evidence-extension-binding.mjs',
  'conformance/validator-evidence-fixture-support.mjs',
  'conformance/validator-evidence-fresh-replacement.mjs',
  'conformance/validator-evidence-fresh-report.mjs',
  'conformance/validator-evidence-mark-stale-churn.mjs',
  'conformance/validator-evidence-nested-subjects.mjs',
  'conformance/validator-evidence-readback-replay.mjs',
  'conformance/validator-evidence-recovery-resolution.mjs',
  'conformance/validator-evidence-stale-recovery.mjs',
  'conformance/validator-evidence-stale-semantics.mjs',
  'conformance/validator-evidence-support.mjs',
  'conformance/validator-evidence-table-validation.mjs',
  'conformance/validator-evidence-transitive-bindings.mjs',
  'conformance/validator-evidence-verdict-resolution.mjs',
  'conformance/validator-final-review-cases.mjs',
  'conformance/validator-review-round-two-cases.mjs',
  'conformance/validator-review-round-three-cases.mjs',
  'conformance/validator-fixture-cases.mjs',
  'conformance/validator-meta-schema-cases.mjs',
  'conformance/validator-package-cases.mjs',
  'conformance/validator-precondition-cases.mjs',
  'conformance/validator-rules.mjs',
  'conformance/validator-security-cases.mjs',
  'conformance/validator-test-support.mjs',
  'conformance/validator-evidence-checks.mjs',
  'conformance/validator-transition-cases.mjs',
  'conformance/validation-report.mjs',
  'conformance/validator.mjs',
  'conformance/validator.test.mjs',
  'conformance/validator-semantic-kernel-cases.mjs',
  'conformance/validator-semantic-kernel-boundary-cases.mjs',
  'conformance/validator-semantic-kernel-review-cases.mjs',
  'conformance/vault-mutation-gate-checks.mjs',
  'conformance/vault-mutation-digests.mjs',
  'conformance/vault-mutation-gate-observer.mjs',
  'conformance/vault-mutation-virtual-vault.mjs',
  'conformance/validator-vault-mutation-gate-cases.mjs',
  'conformance/vault-mutation-recovery-checks.mjs',
  'conformance/reference-vault-core.mjs',
  'conformance/reference-vault-checks.mjs',
  'conformance/reference-vault-observer.mjs',
  'conformance/reference-vault-evidence.mjs',
  'conformance/validator-reference-vault-cases.mjs',
  'conformance/generate-intelligence-adapter-artifacts.mjs',
  'conformance/intelligence-adapter-core.mjs',
  'conformance/intelligence-adapter-validation.mjs',
  'conformance/intelligence-adapter-observer.mjs',
  'conformance/intelligence-adapter-checks.mjs',
  'conformance/validator-intelligence-adapter-cases.mjs',
]);

export function authorityMatches(command, actual) {
  const expected = authorityByCommand.get(command);
  return expected !== undefined && actual !== null && typeof actual === 'object' &&
    Array.isArray(actual.roles) &&
    JSON.stringify(actual.roles) === JSON.stringify(expected.roles) &&
    actual.quorum === expected.quorum &&
    actual.distinct_actors === expected.distinct_actors &&
    actual.delegation === expected.delegation;
}

export function packageArtifactPathAllowed(path) {
  if (typeof path !== 'string') return false;
  if (/^(?:README|product|architecture|operations|security-and-privacy|performance)\.md$/.test(path)) return true;
  if (/^(?:package-manifest|traceability|claims-and-evidence)\.yaml$/.test(path)) return true;
  if (/^normative\/[a-z0-9][a-z0-9./-]*\.(?:md|json|yaml)$/.test(path)) return true;
  if (/^contracts\/[a-z0-9][a-z0-9./-]*\.json$/.test(path)) return true;
  if (path.endsWith('.mjs')) return conformanceExecutables.has(path);
  return /^conformance\/[A-Za-z0-9][A-Za-z0-9./-]*\.(?:md|json|yaml|txt)$/.test(path);
}
